apiVersion: apps/v1
kind: Deployment
metadata:
  name: pingpong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pingpong
  template:
    metadata:
      labels:
        app: pingpong
    spec:
      volumes:
        - name: log-output-vol
          persistentVolumeClaim:
            claimName: log-output-pvc
      containers:
        - name: pingpong
          image: pingpong:latest
          imagePullPolicy: Never
          volumeMounts:
            - name: log-output-vol
              mountPath: /usr/src/app/files

