apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: log-output-pvc
  namespace: exercises
spec:
  storageClassName: log-output-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
